- AppTop/AppCore/BpmSim[1]:
      - Command:               !<value> Halt
      - PeriodInt:             !<value> 256
      - PeriodFract:           !<value> 1234
      - Channels/FilterCoeffs: !<value> 0
      - Channels/PolyCoeffs:   !<value> 0
      - Channels/QScale:       !<value> 20000
      - Channels[0]/QScale:    !<value> 0
      - Channels/NoiseAtt:     !<value> 0
      - Channels[0]/FilterCoeffs[0-31]:
        - 14023
        - 7190
        - -8964
        - 17247
        - 10698
        - -9163
        - -85334
        - -105089
        - -20242
        - -10623
        - 26270
        - -18701
        - -50589
        - 1598
        - -32633
        - -40461
        - 18076
        - -7469
        - -27999
        - -41424
        - 51293
        - 33127
        - -18397
        - 41333
        - -19532
        - 21139
        - -10567
        - 23899
        - -4148
        - -25561
        - -50182
        - 44042
      - Channels[0]/PolyCoeffs[0-119]:
        - 22
        - 64
        - -492
        - -105
        - -566
        - -2552
        - 10422
        - 3379
        - 1311
        - 16461
        - 36
        - 12
        - 335
        - -406
        - -1729
        - -200
        - -6093
        - 8483
        - 13181
        - -699
        - 50
        - 33
        - -126
        - 243
        - -1978
        - -1547
        - 3542
        - -4271
        - 12535
        - 11508
        - -508
        - -188
        - 1241
        - -1937
        - 11458
        - 7820
        - -27334
        - 17875
        - -35447
        - -42277
        - 254
        - -106
        - -1458
        - 1475
        - -4473
        - 590
        - 23448
        - -19918
        - 7510
        - 7340
        - -203
        - -4
        - -31
        - -938
        - 5373
        - 1509
        - -4780
        - 10858
        - -20603
        - -11824
        - 2518
        - -1344
        - 2667
        - 6832
        - -36637
        - 10790
        - 6450
        - -53164
        - 76333
        - -4515
        - -674
        - -571
        - -4610
        - -3057
        - 13947
        - 10917
        - 21740
        - 13301
        - -37539
        - -28080
        - 718
        - -42
        - -1264
        - 2185
        - -8300
        - -1756
        - 14035
        - -13536
        - 12887
        - 8511
        - -3087
        - 2935
        - -4811
        - -2686
        - 28359
        - -24571
        - 15464
        - 16698
        - -40135
        - 31520
        - -1536
        - 1920
        - 6950
        - -3761
        - 11029
        - -15409
        - -32718
        - 19588
        - -11420
        - 18782
        - -658
        - -547
        - 5759
        - -4681
        - 3809
        - 6288
        - -26047
        - 19297
        - -2350
        - -10614
      - Channels[1]/FilterCoeffs[0-39]:
        - -62
        - 587
        - 661
        - -167
        - 670
        - 864
        - -85334
        - -105089
        - 917
        - -1301
        - -2182
        - 3130
        - 717
        - -4576
        - -32633
        - -40461
        - 13278
        - -2994
        - -12698
        - -13971
        - 11768
        - 7479
        - -95792
        - 93641
        - -3446
        - 916
        - 5799
        - 8455
        - -8891
        - -8195
        - -18397
        - 41333
        - 880
        - 775
        - -2586
        - 1970
        - -4029
        - 4428
        - -50182
        - 44042
      - Channels[1]/PolyCoeffs[0-149]:
        - 3
        - 0
        - 8
        - 22
        - -128
        - -25
        - -105
        - -440
        - 892
        - 276
        - -2
        - 2
        - 12
        - 4
        - 89
        - -106
        - -291
        - -41
        - -533
        - 728
        - 0
        - -2
        - 17
        - 11
        - -31
        - 65
        - -342
        - -262
        - 294
        - -375
        - 7
        - 31
        - -231
        - -39
        - 156
        - -766
        - 2877
        - 1245
        - -2093
        - 2658
        - 6
        - -13
        - 132
        - -72
        - -366
        - 450
        - -1374
        - 512
        - 2247
        - -2179
        - 9
        - 11
        - -82
        - 17
        - -119
        - -325
        - 1191
        - 94
        - -82
        - 1342
        - 551
        - -136
        - -219
        - 2124
        - -7579
        - 1507
        - 2363
        - -14982
        - 16652
        - -2473
        - -412
        - -411
        - -1108
        - -918
        - 5900
        - 5844
        - 7081
        - 5765
        - -13479
        - -13280
        - 335
        - 164
        - -1279
        - 1614
        - -4404
        - -2557
        - 9409
        - -10977
        - 9212
        - 6299
        - -458
        - 288
        - -745
        - -1213
        - 6941
        - -2583
        - 390
        - 9881
        - -15027
        - 2077
        - 102
        - 91
        - 959
        - 647
        - -2388
        - -1908
        - -4866
        - -3084
        - 6829
        - 5175
        - -141
        - 19
        - 183
        - -422
        - 1705
        - 187
        - -2363
        - 2718
        - -2828
        - -1354
        - -129
        - -120
        - 1202
        - -962
        - 724
        - 1355
        - -5421
        - 3953
        - -396
        - -2265
        - 248
        - -145
        - 365
        - -579
        - -2270
        - 1450
        - -1151
        - 2254
        - 3203
        - -2211
        - 199
        - -151
        - 87
        - 308
        - -1755
        - 1206
        - -33
        - -1594
        - 2384
        - -1463
      - Channels[2]/FilterCoeffs[0-39]:
        - -153
        - 789
        - 969
        - -315
        - 888
        - 1255
        - -85334
        - -105089
        - 2469
        - -130
        - -3996
        - 4106
        - 4910
        - -3796
        - -32633
        - -40461
        - -5555
        - 5168
        - 6928
        - -7585
        - -4955
        - 7079
        - -109203
        - -34060
        - -566
        - -1131
        - 2115
        - 2796
        - 779
        - -6088
        - -18397
        - 41333
        - 274
        - 331
        - -965
        - 772
        - -1475
        - 1550
        - -50182
        - 44042
      - Channels[2]/PolyCoeffs[0-149]:
        - 4
        - 0
        - 14
        - 31
        - -177
        - -23
        - -197
        - -633
        - 1244
        - 309
        - -4
        - 3
        - 15
        - 8
        - 133
        - -148
        - -379
        - -98
        - -809
        - 1023
        - 0
        - -3
        - 25
        - 15
        - -34
        - 98
        - -496
        - -346
        - 352
        - -581
        - 49
        - 41
        - -291
        - 135
        - -857
        - -1283
        - 4644
        - -537
        - 1365
        - 5750
        - -17
        - -1
        - 230
        - -184
        - 90
        - 310
        - -3109
        - 2117
        - 1153
        - -2371
        - 25
        - 10
        - -63
        - 94
        - -556
        - -389
        - 1362
        - -855
        - 1700
        - 2087
        - 7
        - -104
        - 583
        - 102
        - -256
        - 2331
        - -6598
        - -1417
        - 1312
        - -8497
        - -26
        - 96
        - -529
        - 108
        - 676
        - -2201
        - 5944
        - -987
        - -2818
        - 8152
        - -12
        - -93
        - 515
        - -6
        - 190
        - 2106
        - -5875
        - -166
        - -372
        - -7740
        - -20
        - 128
        - -718
        - 27
        - 1031
        - -1750
        - 4148
        - 983
        - -3666
        - 3410
        - -50
        - -30
        - 361
        - 269
        - 290
        - 122
        - -2619
        - -1890
        - 296
        - 400
        - -35
        - 32
        - -118
        - -84
        - 588
        - -341
        - 399
        - 794
        - -1402
        - 454
        - -54
        - -37
        - 426
        - -356
        - 330
        - 435
        - -1935
        - 1476
        - -238
        - -750
        - 87
        - -48
        - 149
        - -219
        - -799
        - 491
        - -495
        - 865
        - 1138
        - -760
        - 71
        - -56
        - 45
        - 101
        - -629
        - 453
        - -73
        - -534
        - 861
        - -557
      - Channels[3]/FilterCoeffs[0-39]:
        - -79
        - 1064
        - 1160
        - -260
        - 1219
        - 1523
        - -85334
        - -105089
        - 1754
        - -2430
        - -4139
        - 5910
        - 1421
        - -8604
        - -32633
        - -40461
        - 15803
        - 8503
        - -22947
        - -24704
        - 11706
        - 22975
        - -80905
        - 67982
        - -5031
        - -1283
        - 10846
        - 15226
        - -8402
        - -21667
        - -18397
        - 41333
        - 974
        - 1317
        - -3676
        - 2991
        - -5581
        - 5773
        - -50182
        - 44042
      - Channels[3]/PolyCoeffs[0-149]:
        - 5
        - 1
        - 13
        - 39
        - -230
        - -50
        - -165
        - -778
        - 1596
        - 530
        - -4
        - 4
        - 22
        - 7
        - 155
        - -190
        - -534
        - -55
        - -922
        - 1297
        - 1
        - -3
        - 31
        - 20
        - -60
        - 112
        - -602
        - -477
        - 551
        - -645
        - 14
        - 59
        - -436
        - -70
        - 278
        - -1451
        - 5447
        - 2314
        - -3883
        - 5057
        - 12
        - -24
        - 250
        - -138
        - -682
        - 846
        - -2617
        - 991
        - 4212
        - -4106
        - 18
        - 22
        - -154
        - 33
        - -231
        - -613
        - 2246
        - 162
        - -125
        - 2539
        - 711
        - -423
        - 1161
        - 2582
        - -11118
        - 5647
        - -6789
        - -20775
        - 27749
        - -11724
        - -419
        - -193
        - -2122
        - -2470
        - 6986
        - 3656
        - 14907
        - 18183
        - -18476
        - -10686
        - 557
        - -80
        - -315
        - 2241
        - -8345
        - 553
        - 3964
        - -17223
        - 19942
        - 338
        - -556
        - 586
        - -2307
        - -1308
        - 9913
        - -6483
        - 8922
        - 13120
        - -24393
        - 9310
        - 12
        - 40
        - 1816
        - 1277
        - -2092
        - -1896
        - -10829
        - -7335
        - 8283
        - 6637
        - -230
        - 88
        - -35
        - -647
        - 3120
        - -487
        - -1841
        - 4681
        - -6048
        - -595
        - -214
        - -129
        - 1592
        - -1353
        - 1334
        - 1566
        - -7256
        - 5627
        - -1024
        - -2732
        - 322
        - -176
        - 585
        - -840
        - -2984
        - 1807
        - -1972
        - 3329
        - 4260
        - -2810
        - 265
        - -214
        - 189
        - 367
        - -2364
        - 1731
        - -357
        - -1957
        - 3245
        - -2136
      - Command:               !<value> Run
